### PR TITLE
Acceseblity check

### PR DESCRIPTION
**Pull request by rozhi-98**
# We have removed all accessibility errors and the website passes all the checks by 
- Added updated index.html file in the case of accessibility
- Added style.css file

### CODE REVIEW

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
Hi Team, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 

## Highlights 💪 
- No linter errors
- correct flow is used
- good PR

## Required Changes ♻️

- [ ] good job so far guys 👏 👏 I would suggest that you add the report of your work in the Pull request description as it is in the project requirements 😃  Please take a look at the screenshot below 👇
image

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by girma336** [comment]
# We have removed all accessibility errors and the website passes all the checks by
  - Added updated index.html file
  - Added style.css file

**Review by Abenezer-Tilahun — CHANGES_REQUESTED** [review]
Hi Team  , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct GitHub Flow.
✔️ Professional   README
✔️ Good commit messages

almost

## Required Changes ♻️

- [x] As stated in the project requirement and suggested by the previous reviewer   I would suggest that you add the report of your work in the Pull request description as it is in the project requirements 😃 Please take a look at the screenshot below 👇
Capture

_Check the comments below the review._

## Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by girma336** [comment]
# We have removed all accessibility errors and the website passes all the checks by
  - Added title name Responsive Personal Portfolio Project | Review of Web Accessibility [correction] ( https://github.com/girma336/girma336.github.io/blob/Acceseblity_check/index.html#L7)
  - Image text alternatives: no issues found
  - Text Heading: changed all heading according to accessibility requirements 
  - Color contrast: no issues found
  -  Resize: no issues found
  -  Interaction: no issues found 
  - Moving content: no issues found
  -  Multimedia: no issues found
  - The basic structure of the page: no issues found

**Review by cynthiainga — APPROVED** [review]
## STATUS APPROVED ✔️ ✔️ 

Hi @rozhi-98 & @girma336, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Correct Github flow ✔️ 
- [ ] Good commit history ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
